name: Telegram NewsPic AutoPost

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 (원하면 나중에 변경)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: npm run start
        env:
          NEWSPIC_COOKIE: ${{ secrets.NEWSPIC_COOKIE }}
